ALTER TABLE Productions
ADD CONSTRAINT TheaterFK
FOREIGN KEY(theaterID)
REFERENCES Theaters
ON UPDATE SET NULL;

ALTER TABLE Productions
ADD CONSTRAINT DirectorFK
FOREIGN KEY(directorID)
REFERENCES Persons(personID)
ON DELETE SET NULL
ON UPDATE CASCADE;

ALTER TABLE Roles
ADD CONSTRAINT PlayTitleCharNameFK
FOREIGN KEY(playTitle, characterName)
REFERENCES Characters;